name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get Schemes
        run: |
          xcodebuild -list -project "Obj-C/AdGem-ObjC.xcodeproj"
          xcodebuild -list -project "Swift/AdGemTester.xcodeproj"

      - name: Build Objective-C project
        run: /usr/bin/xcodebuild -project "Obj-C/AdGem-ObjC.xcodeproj" -scheme "AdGem-ObjC" -destination 'generic/platform=iOS Simulator' build

      - name: Build Swift project
        run: /usr/bin/xcodebuild -project "Swift/AdGemTester.xcodeproj" -scheme "AdGemTester" -destination 'generic/platform=iOS Simulator' build
